---
title: "PCA plot"
author: "Gabriel Luis Hernandez"
output:
  pdf_document: default
  html_document: default
---
```{r echo=FALSE, message=FALSE, warning=FALSE}
libraries <- c("ggplot2", "gdsfmt", "SNPRelate", "MASS", "tidyverse", "ggtext", "ggrepel")
for (lib in libraries) {
  if (require(package = lib, character.only = TRUE)) {
    print("Successful")
  } else {
    print("Installing")
    if (!requireNamespace("BiocManager", quietly = TRUE)) {
      install.packages("BiocManager")
    }
    BiocManager::install(lib)
    library(lib, character.only = TRUE)
  }
}
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
updated_tab <- read.csv("input/outgroup_edited.csv", header = TRUE, fill = TRUE)

Xlabs <- paste("PC2 ", PCA2, "%", sep = "")
Ylabs <- paste("PC1 ", PCA1, "%", sep = "")
```

# pca plot

```{r echo=FALSE, warning=FALSE}

pca_plot <- ggplot(data = updated_tab %>% arrange(desc(pop)), aes(x = EV1, y = EV2,)) +
              geom_point(aes(color=pop, stroke = 0.9, shape= super), 
              alpha=0.6, size = 2) + 
              guides(fill=FALSE, alpha=FALSE, size=FALSE) + 
             labs(shape = "Supergene variant", color="Species", 
                  x =Xlabs, y = Ylabs)

pca_plot_print <- pca_plot + scale_shape_manual(values = c(21, 24, 3, 22)) + 
                   scale_colour_manual(values=c("#000000", "#ff0600", 
                                                "#d87904","#891bce", 
                                                "#f71ae6", "#2bc100"), 
                    labels = c("S. 'AdRX'","*S. interrupta*","*S. invicta*", 
                               "*S. macdonaghi*", "*S. megergates*",
                               "*S. richteri*")) +
                   theme(legend.text = element_markdown(size = 8),
                         legend.title = element_text(size = 9))+
  theme_minimal()
  
  
pca_plot_print

```
